In [1]:
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
%matplotlib inline
import cv2

In [2]:
data = genfromtxt('Computer-Vision-with-Python/DATA/bank_note_data.txt',delimiter=',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [9]:
labels = data[:,4]
labels
features = data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [11]:
X = features
y = labels

from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [26]:
from sklearn.preprocessing import MinMaxScaler
scaler_object = MinMaxScaler()
scaler_object.fit(X_train)
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

scaled_X_train

from keras.models import Sequential
from keras.layers import Dense

In [29]:
model = Sequential()
model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

model.add(Dense(1,activation='sigmoid'))



In [33]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.0511 - acc: 0.9793
Epoch 2/50
 - 0s - loss: 0.0503 - acc: 0.9826
Epoch 3/50
 - 0s - loss: 0.0511 - acc: 0.9804
Epoch 4/50
 - 0s - loss: 0.0499 - acc: 0.9782
Epoch 5/50
 - 0s - loss: 0.0494 - acc: 0.9782
Epoch 6/50
 - 0s - loss: 0.0485 - acc: 0.9804
Epoch 7/50
 - 0s - loss: 0.0489 - acc: 0.9793
Epoch 8/50
 - 0s - loss: 0.0490 - acc: 0.9848
Epoch 9/50
 - 0s - loss: 0.0475 - acc: 0.9771
Epoch 10/50
 - 0s - loss: 0.0467 - acc: 0.9771
Epoch 11/50
 - 0s - loss: 0.0465 - acc: 0.9782
Epoch 12/50
 - 0s - loss: 0.0459 - acc: 0.9782
Epoch 13/50
 - 0s - loss: 0.0456 - acc: 0.9761
Epoch 14/50
 - 0s - loss: 0.0448 - acc: 0.9804
Epoch 15/50
 - 0s - loss: 0.0463 - acc: 0.9804
Epoch 16/50
 - 0s - loss: 0.0457 - acc: 0.9793
Epoch 17/50
 - 0s - loss: 0.0433 - acc: 0.9804
Epoch 18/50
 - 0s - loss: 0.0434 - acc: 0.9793
Epoch 19/50
 - 0s - loss: 0.0431 - acc: 0.9815
Epoch 20/50
 - 0s - loss: 0.0426 - acc: 0.9793
Epoch 21/50
 - 0s - loss: 0.0426 - acc: 0.9804
Epoch 22/50
 - 0s - lo

In [35]:
#model.predict_classes(scaled_X_test)
model.metrics_names
from sklearn.metrics import confusion_matrix,classification_report
predictions = model.predict_classes(scaled_X_test)
confusion_matrix(y_test,predictions)

array([[253,   4],
       [  2, 194]], dtype=int64)

In [37]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.99      0.98      0.99       257
        1.0       0.98      0.99      0.98       196

avg / total       0.99      0.99      0.99       453



In [38]:
model.save('wowmodel.h5')